### ISSUE TITLE
HTML report is not created with TEAM Engine 5.0 when using Web Browser Interface

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#17]
Instead, behaviour as described in https://github.com/opengeospatial/teamengine/issues/251 can be observed.

Can be reproduced on http://cite.opengeospatial.org/te2/ .

**Comment by keshavnangare** [comment]
@dstenger 

HTML report is not generated due to testng-results.xml and earl-results.rdf file is not present in the log  directory.

If the earl-result.rdf file is not present in log directory then it will not generate HTML report.

**Comment by lgoltz** [comment]
Should be fixed with https://github.com/opengeospatial/teamengine/pull/256

**Comment by dstenger** [comment]
Fix for opengeospatial/teamengine#256 has been created.

Test with the branch containing the fix:

Start TEAM Engine and execute test suite via Web Browser Interface with http://www.geopackage.org/data/gdal_sample_v1.2_no_extensions.gpkg.

=> The old test result can be viewed making the test suite usable with Web Browser Interface again.

However, I am wondering why the new HTML report is not generated (this is a TestNG test suite).
@keshav-nangare Can you please do further investigations?

**Comment by keshavnangare** [comment]
@dstenger 

The teamengine is not creating the new HTML report due to the absence of earl-results.rdf file in the session directory.

The gpkg12 test is creating  testng-results.xml and earl-results.rdf files in `$CATALINA_BASE\temp ` directory, when teamengine is trying to generate new HTML report from the earl-results.rdf and its not present in result directory then it will skip the HTML report.

The gpkg12 has the incorrect  URI of outputDir so it creating the testng result in temp directory.

I have fixed this issue with this commit: 2923a74f895908ec0598c7d288a5ce68f76e5d8c
