### ISSUE TITLE
No requirement can be found for test "feature S R Sconsistency"

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#78]
Test: https://github.com/opengeospatial/ets-gpkg12/blob/477026324c88313316275fd19d74014be164641d/src/main/java/org/opengis/cite/gpkg12/features/FeaturesTests.java#L304-L361

Test fails because the results of two sql statements are not equal (first if):
 * SELECT count(*) as ggcCount FROM 'gpkg_geometry_columns';
   * returns 68
 * SELECT count(*) as ggcCount FROM 'gpkg_contents' WHERE data_type = 'features';
   * returns 34

The test expects that both counts are equal.

In http://www.geopackage.org/spec/ I cannot find a test case with id `/base/core/contents/data/table_def/srs_id`, and I don't see that Requirement 13 makes the test necessary. 
Furthermore the if-else-statement in the end of the test can be simplified.

**Comment by jyutzler** [comment]
What is the test file that reproduces the false-positive?
BTW, this test was added as part of https://github.com/opengeospatial/ets-gpkg12/commit/acbf3c57280b9f65f29b0a8bc63125f4e0635330#diff-cd87833e776c4a923a7e470580031367

**Comment by ajanett** [comment]
Since this test is not in the current spec, it is only implied by requirement 13; and due to the fact that the test is being added to the upcoming specification, I recommend that this version of the test be removed at this time until it can be added for the upcoming specification.

**Comment by lgoltz** [comment]
@ajanett, @jyutzler 
Shall we remove the test completely or implement Requirement 13 as it is specified in 1.2?

**Comment by jyutzler** [comment]
@lgoltz I do not feel comfortable answering this question until I can see a proper test case. Without it, I can't envision how we can go wrong.

**Comment by lgoltz** [comment]
@jyutzler The test fails with https://hawk.compusult.net/ogc/PR_GGDM_3.0_Profile_File_Geodatabase.gpkg

**Comment by ajanett** [comment]
The issue is that since srs_id is held in both gpkg_contents and gpkg_geometry_columns, it is possible for data integrity issues to occur.

The test is to ensure that for each table_name within gpkg_contents, verify that srs_id is consistent between gpkg_contents and gpkg_geometry_columns. 
  
A better SQL for this test for the FEATURES is:
SELECT gpkg_geometry_columns.table_name, gpkg_geometry_columns.srs_id FROM gpkg_geometry_columns INNER JOIN gpkg_contents ON (gpkg_geometry_columns.table_name = gpkg_contents.table_name) WHERE (gpkg_contents.data_type = 'features' and gpkg_contents.srs_id != gpkg_geometry_columns.srs_id);
Fail if the SQL returns any rows

**Comment by ajanett** [comment]
Requirement 146 was added to the specification to specifically address this issue and I believe that requirement is also coded into the ets-gpkg20. Therefore the FeatureSRSConsistency method may be removed and this issue can be closed.

**Comment by jyutzler** [comment]
My assessment is that the check comparing the row counts of `gpkg_data_columns` to row counts of `gpkg_contents` where datatype="features" is invalid because there may be extensions that use `gpkg_data_columns` with a different datatype. 

This test file is a bit big to add to the ETS so I will reproduce the issue elsewhere. 

Since there is already a test for R146 at FeaturesTests.featureGeometryColumnsDataValuesSrsId(), I see no need for the existing FeaturesTests.featureSRSconsistency().

**Comment by keshavnangare** [comment]
@dstenger 

 We are fine with the solution and changes are successfully tested on the local environment.
