### ISSUE TITLE
A `-` in the table name breaks the ETS

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/ets-gpkg12#93]
The ETS is vulnerable to dubious identifier names. For example, in TableVerifier.java L54, we have the following prepared statement.

`        try(final PreparedStatement statement = connection.prepareStatement("SELECT sql FROM sqlite_master WHERE (type = 'table' OR type = 'view') AND tbl_name = ?;"))`

Most of the time, this works fine but I recently found a GPKG with a table with a `-` in its name. This causes the whole prepared statement to fail (which seems to defeat the purpose of prepared statements, but I digress). 

 It will require a thorough sweep of the ETS to identify and eliminate all of these vulnerabilities.

**Comment by dstenger** [comment]
@keshav-nangare Can you please take a look at this?

**Comment by keshavnangare** [comment]
@jyutzler 

Do you have any `.gpkg` file which I can use for testing?

**Comment by jyutzler** [comment]
Not really. The problem is easily duplicated, but since I do not know how pervasive the problem is, I am reluctant to provide a file which might or might not address all of the failure points.

You can take any GeoPackage, pick a table from gpkg_contents, and issue:
`create table "table-with-dash" as select * from your_table`

Copy the relevant row from gpkg_contents (replacing the table_name) and you should be off and running.

**Comment by keshavnangare** [comment]
Ok. Thanks for the inputs.

**Comment by keshavnangare** [comment]
@dstenger 

I am able to reproduce the issue on local environment with the following workaround:

1. Used test resource gpkg file(e.g. sample1_0.gpkg).
2. Alter the existing table name(`counties`) to `count-ies`.
3.  Executed test suite but multiple tests were failed.
4. I went through the failed tests and accordingly I have updated references of table which are present in other tables.
5. Got failure while extensionsColumnValues() test because of "-" in table name. It was not able to find table in the database.
6. Fixed extensionsColumnValues() test by adding single quote to table name.

**Comment by keshavnangare** [comment]
@jyutzler 

Fixed with #97 PR.
Can you test it?

**Comment by jyutzler** [comment]
This is currently assigned to me, but there is not an open pull request that addresses the issue. Please re-assign.

**Comment by dstenger** [comment]
@jyutzler If I understand correctly, this issue is on hold due to the changes made by @ajanett as described in https://github.com/opengeospatial/ets-gpkg12/pull/97#issuecomment-670806747 and the discussion in https://github.com/opengeospatial/geopackage/issues/501.
Do you think we can close this issue or should we keep it open?
Another option would be to enhance the documentation describing the restriction of the test suite.

**Comment by ghobona** [comment]
@dstenger Let's update the documentation describing the restriction of the test suite.

**Comment by dstenger** [comment]
@jyutzler Shall we add the list of comment https://github.com/opengeospatial/geopackage/issues/501#issue-505326216 as precondition to the documentation of the test suite?
Can you please confirm this? I can update the documentation then.

**Comment by dstenger** [comment]
@dstenger is adding following sentence to documentation:

The executable test suite restricts identifiers to contain alphanumeric characters and underscores.

**Comment by dstenger** [comment]
Precondition was added to documentation: https://github.com/opengeospatial/ets-gpkg12/commit/4f3dd64f4ba3198d8f79622500c5e44c725529f7
